# Generated by Django 3.2.6 on 2021-08-12 19:39

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songususer',
            name='avatar',
            field=models.ImageField(blank=True, default=web.models.get_default_avatar_img, null=True, upload_to='profiles'),
        ),
    ]
