# Generated by Django 3.2.6 on 2021-08-12 19:52

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_songususer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default=web.models.get_default_group_avatar_img, null=True, upload_to='groupprofiles'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='avatar',
            field=models.ImageField(blank=True, default=web.models.get_default_playlist_cover_img, null=True, upload_to='playlistcover'),
        ),
    ]
