# Generated by Django 3.2.6 on 2021-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210813_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='memeber',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member', to='web.songususer'),
        ),
    ]
