# Generated by Django 3.2.6 on 2021-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210813_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='web.songususer'),
        ),
    ]
