# Generated by Django 3.2.3 on 2021-08-13 15:56

from django.db import migrations, models
import web.utils


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_group_joincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=web.utils.get_file_upload_path, verbose_name='File')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('artist', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
