# Generated by Django 3.2.6 on 2021-08-14 14:12

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_playlist_favoritve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='joincode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PersonalPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, default=web.models.get_default_playlist_cover_img, null=True, upload_to='playlistcover')),
                ('favoritve', models.ManyToManyField(blank=True, null=True, related_name='personalfavorites', to='web.songususer')),
            ],
        ),
    ]
