# Generated by Django 3.2.6 on 2021-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210814_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalplaylist',
            name='favoritve',
        ),
        migrations.AddField(
            model_name='personalplaylist',
            name='isfav',
            field=models.BooleanField(default=False),
        ),
    ]
