# Generated by Django 3.2.6 on 2021-08-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_personalplaylist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='issuggested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='PersonalPlaylist',
        ),
    ]
