# Generated by Django 3.2.6 on 2021-08-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_group_isprivate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
