# Generated by Django 3.2.6 on 2021-08-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20210818_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='issuggested',
            new_name='is_suggested',
        ),
    ]
