# Generated by Django 3.2.6 on 2021-08-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_issuggested_song_is_suggested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='recentmusic',
            new_name='recent_music',
        ),
    ]
