# Generated by Django 3.2.6 on 2021-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_rename_recentmusic_song_recent_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='recent_music',
            field=models.ManyToManyField(blank=True, null=True, related_name='recent_music', to='web.songususer'),
        ),
    ]
