# Generated by Django 3.2.6 on 2021-08-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_song_recent_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='isprivate',
            new_name='is_private',
        ),
    ]
