# Generated by Django 3.2.3 on 2021-08-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_rename_isprivate_group_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.songususer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.song')),
            ],
        ),
    ]
