# Generated by Django 3.2.6 on 2021-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_song_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
