# Generated by Django 3.2.6 on 2021-08-24 16:06

from django.db import migrations, models
import web.utils


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_song_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=web.utils.get_file_upload_path, verbose_name='File'),
        ),
    ]
