# Generated by Django 3.2.6 on 2021-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperoryaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('isactivenow', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
